2025-06-18 15:20:58,134 INFO - START CREATED ToolCallLLM(adder Node, multiplier Node)
2025-06-18 15:21:01,960 INFO - ToolCallLLM(adder Node, multiplier Node) DONE
2025-06-18 15:21:55,593 INFO - START CREATED ToolCallLLM(adder Node, multiplier Node)
2025-06-18 15:21:57,797 INFO - ToolCallLLM(adder Node, multiplier Node) DONE
2025-06-18 15:22:08,525 INFO - START CREATED ToolCallLLM(adder Node, multiplier Node)
2025-06-18 15:22:11,145 INFO - ToolCallLLM(adder Node, multiplier Node) CREATED multiplier Node
2025-06-18 15:22:11,147 INFO - ToolCallLLM(adder Node, multiplier Node) CREATED adder Node
2025-06-18 15:22:11,147 INFO - multiplier Node DONE
2025-06-18 15:22:11,147 INFO - adder Node DONE
2025-06-18 15:22:11,741 INFO - ToolCallLLM(adder Node, multiplier Node) DONE
2025-06-18 15:23:13,533 INFO - START CREATED ToolCallLLM(multiplier Node, adder Node)
2025-06-18 15:23:15,087 INFO - ToolCallLLM(multiplier Node, adder Node) DONE
2025-06-18 15:23:48,139 INFO - START CREATED ToolCallLLM(adder Node, multiplier Node)
2025-06-18 15:23:49,028 INFO - ToolCallLLM(adder Node, multiplier Node) CREATED multiplier Node
2025-06-18 15:23:49,029 ERROR - multiplier Node FAILED
Traceback (most recent call last):
  File "C:\Users\Logan\Documents\rc\src\requestcompletion\execution\execution_strategy.py", line 54, in execute
    result = await invoke_func()
  File "C:\Users\Logan\Documents\rc\src\requestcompletion\execution\task.py", line 23, in invoke
    return await self.node.invoke()
  File "C:\Users\Logan\Documents\rc\src\requestcompletion\nodes\nodes.py", line 44, in async_wrapper
    return await asyncio.to_thread(method, self, *args, **kwargs)
  File "C:\Users\Logan\AppData\Local\Programs\Python\Python310\lib\asyncio\threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "C:\Users\Logan\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Logan\Documents\rc\src\requestcompletion\nodes\library\function.py", line 68, in invoke
    result = func(*self.args, **self.kwargs)
  File "C:\Users\Logan\Documents\rc\experiments\sandbox.py", line 28, in multiplier
    raise Exception("Mutiplier is broken, use other functions to calculate the result")
Exception: Mutiplier is broken, use other functions to calculate the result
2025-06-18 15:23:51,673 INFO - ToolCallLLM(adder Node, multiplier Node) CREATED adder Node
2025-06-18 15:23:51,675 INFO - ToolCallLLM(adder Node, multiplier Node) CREATED adder Node
2025-06-18 15:23:51,677 INFO - ToolCallLLM(adder Node, multiplier Node) CREATED adder Node
2025-06-18 15:23:51,678 INFO - ToolCallLLM(adder Node, multiplier Node) CREATED adder Node
2025-06-18 15:23:51,678 INFO - adder Node DONE
2025-06-18 15:23:51,678 INFO - adder Node DONE
2025-06-18 15:23:51,678 INFO - adder Node DONE
2025-06-18 15:23:51,679 INFO - adder Node DONE
2025-06-18 15:23:52,679 INFO - ToolCallLLM(adder Node, multiplier Node) CREATED adder Node
2025-06-18 15:23:52,682 INFO - adder Node DONE
2025-06-18 15:23:53,310 INFO - ToolCallLLM(adder Node, multiplier Node) CREATED adder Node
2025-06-18 15:23:53,324 INFO - adder Node DONE
2025-06-18 15:23:53,968 INFO - ToolCallLLM(adder Node, multiplier Node) DONE
